### PR TITLE
Img tag is now able to be converted in JSX

### PR DESCRIPTION
**Pull request by Axxi3**

### CODE REVIEW

**Comment by pythonpioneer** [comment]
"img" tags can now convert into JSX but the other requirements are not working. 

You can **reproduce** it with:
```{r}
input: <img class="demo" for="demo">
output: <img class="demo" for="demo"/>
expected output: <img className="demo" htmlFor="demo"/>
```

**Comment by Axxi3** [comment]
ohh wait I'll look into it

**Comment by Axxi3** [comment]
@pythonpioneer hey man i fixed the code just have a look

**Review by pythonpioneer — APPROVED** [review]
Issue #1 resolved

**Pull request merged**
